#ifndef ADD_TEST_COMPONENT_SYSTEM_HPP
#define ADD_TEST_COMPONENT_SYSTEM_HPP

#include "TRA/ecs/engine.hpp"
#include "common.hpp"
#include "component.hpp"

struct AddTestComponentSystem : public ecs::ISystem
{
    void update(ecs::Engine* _engine) override
    {
        for (size_t i = 0; i < ENTITY_COUNT; i++)
        {
            int start = rand() % 100;

            switch (start)
            {
            case 0:  _engine->addComponentToEntity(entities[i], TestComponent0{});
                _engine->addComponentToEntity(entities[i], TestComponent1{});
                _engine->addComponentToEntity(entities[i], TestComponent2{});
                break;
            case 1:  _engine->addComponentToEntity(entities[i], TestComponent1{});
                _engine->addComponentToEntity(entities[i], TestComponent2{});
                _engine->addComponentToEntity(entities[i], TestComponent3{});
                break;
            case 2:  _engine->addComponentToEntity(entities[i], TestComponent2{});
                _engine->addComponentToEntity(entities[i], TestComponent3{});
                _engine->addComponentToEntity(entities[i], TestComponent4{});
                break;
            case 3:  _engine->addComponentToEntity(entities[i], TestComponent3{});
                _engine->addComponentToEntity(entities[i], TestComponent4{});
                _engine->addComponentToEntity(entities[i], TestComponent5{});
                break;
            case 4:  _engine->addComponentToEntity(entities[i], TestComponent4{});
                _engine->addComponentToEntity(entities[i], TestComponent5{});
                _engine->addComponentToEntity(entities[i], TestComponent6{});
                break;
            case 5:  _engine->addComponentToEntity(entities[i], TestComponent5{});
                _engine->addComponentToEntity(entities[i], TestComponent6{});
                _engine->addComponentToEntity(entities[i], TestComponent7{});
                break;
            case 6:  _engine->addComponentToEntity(entities[i], TestComponent6{});
                _engine->addComponentToEntity(entities[i], TestComponent7{});
                _engine->addComponentToEntity(entities[i], TestComponent8{});
                break;
            case 7:  _engine->addComponentToEntity(entities[i], TestComponent7{});
                _engine->addComponentToEntity(entities[i], TestComponent8{});
                _engine->addComponentToEntity(entities[i], TestComponent9{});
                break;
            case 8:  _engine->addComponentToEntity(entities[i], TestComponent8{});
                _engine->addComponentToEntity(entities[i], TestComponent9{});
                _engine->addComponentToEntity(entities[i], TestComponent10{});
                break;
            case 9:  _engine->addComponentToEntity(entities[i], TestComponent9{});
                _engine->addComponentToEntity(entities[i], TestComponent10{});
                _engine->addComponentToEntity(entities[i], TestComponent11{});
                break;
            case 10: _engine->addComponentToEntity(entities[i], TestComponent10{});
                _engine->addComponentToEntity(entities[i], TestComponent11{});
                _engine->addComponentToEntity(entities[i], TestComponent12{});
                break;
            case 11: _engine->addComponentToEntity(entities[i], TestComponent11{});
                _engine->addComponentToEntity(entities[i], TestComponent12{});
                _engine->addComponentToEntity(entities[i], TestComponent13{});
                break;
            case 12: _engine->addComponentToEntity(entities[i], TestComponent12{});
                _engine->addComponentToEntity(entities[i], TestComponent13{});
                _engine->addComponentToEntity(entities[i], TestComponent14{});
                break;
            case 13: _engine->addComponentToEntity(entities[i], TestComponent13{});
                _engine->addComponentToEntity(entities[i], TestComponent14{});
                _engine->addComponentToEntity(entities[i], TestComponent15{});
                break;
            case 14: _engine->addComponentToEntity(entities[i], TestComponent14{});
                _engine->addComponentToEntity(entities[i], TestComponent15{});
                _engine->addComponentToEntity(entities[i], TestComponent16{});
                break;
            case 15: _engine->addComponentToEntity(entities[i], TestComponent15{});
                _engine->addComponentToEntity(entities[i], TestComponent16{});
                _engine->addComponentToEntity(entities[i], TestComponent17{});
                break;
            case 16: _engine->addComponentToEntity(entities[i], TestComponent16{});
                _engine->addComponentToEntity(entities[i], TestComponent17{});
                _engine->addComponentToEntity(entities[i], TestComponent18{});
                break;
            case 17: _engine->addComponentToEntity(entities[i], TestComponent17{});
                _engine->addComponentToEntity(entities[i], TestComponent18{});
                _engine->addComponentToEntity(entities[i], TestComponent19{});
                break;
            case 18: _engine->addComponentToEntity(entities[i], TestComponent18{});
                _engine->addComponentToEntity(entities[i], TestComponent19{});
                _engine->addComponentToEntity(entities[i], TestComponent20{});
                break;
            case 19: _engine->addComponentToEntity(entities[i], TestComponent19{});
                _engine->addComponentToEntity(entities[i], TestComponent20{});
                _engine->addComponentToEntity(entities[i], TestComponent21{});
                break;
            case 20: _engine->addComponentToEntity(entities[i], TestComponent20{});
                _engine->addComponentToEntity(entities[i], TestComponent21{});
                _engine->addComponentToEntity(entities[i], TestComponent22{});
                break;
            case 21: _engine->addComponentToEntity(entities[i], TestComponent21{});
                _engine->addComponentToEntity(entities[i], TestComponent22{});
                _engine->addComponentToEntity(entities[i], TestComponent23{});
                break;
            case 22: _engine->addComponentToEntity(entities[i], TestComponent22{});
                _engine->addComponentToEntity(entities[i], TestComponent23{});
                _engine->addComponentToEntity(entities[i], TestComponent24{});
                break;
            case 23: _engine->addComponentToEntity(entities[i], TestComponent23{});
                _engine->addComponentToEntity(entities[i], TestComponent24{});
                _engine->addComponentToEntity(entities[i], TestComponent25{});
                break;
            case 24: _engine->addComponentToEntity(entities[i], TestComponent24{});
                _engine->addComponentToEntity(entities[i], TestComponent25{});
                _engine->addComponentToEntity(entities[i], TestComponent26{});
                break;
            case 25: _engine->addComponentToEntity(entities[i], TestComponent25{});
                _engine->addComponentToEntity(entities[i], TestComponent26{});
                _engine->addComponentToEntity(entities[i], TestComponent27{});
                break;
            case 26: _engine->addComponentToEntity(entities[i], TestComponent26{});
                _engine->addComponentToEntity(entities[i], TestComponent27{});
                _engine->addComponentToEntity(entities[i], TestComponent28{});
                break;
            case 27: _engine->addComponentToEntity(entities[i], TestComponent27{});
                _engine->addComponentToEntity(entities[i], TestComponent28{});
                _engine->addComponentToEntity(entities[i], TestComponent29{});
                break;
            case 28: _engine->addComponentToEntity(entities[i], TestComponent28{});
                _engine->addComponentToEntity(entities[i], TestComponent29{});
                _engine->addComponentToEntity(entities[i], TestComponent30{});
                break;
            case 29: _engine->addComponentToEntity(entities[i], TestComponent29{});
                _engine->addComponentToEntity(entities[i], TestComponent30{});
                _engine->addComponentToEntity(entities[i], TestComponent31{});
                break;
            case 30: _engine->addComponentToEntity(entities[i], TestComponent30{});
                _engine->addComponentToEntity(entities[i], TestComponent31{});
                _engine->addComponentToEntity(entities[i], TestComponent32{});
                break;
            case 31: _engine->addComponentToEntity(entities[i], TestComponent31{});
                _engine->addComponentToEntity(entities[i], TestComponent32{});
                _engine->addComponentToEntity(entities[i], TestComponent33{});
                break;
            case 32: _engine->addComponentToEntity(entities[i], TestComponent32{});
                _engine->addComponentToEntity(entities[i], TestComponent33{});
                _engine->addComponentToEntity(entities[i], TestComponent34{});
                break;
            case 33: _engine->addComponentToEntity(entities[i], TestComponent33{});
                _engine->addComponentToEntity(entities[i], TestComponent34{});
                _engine->addComponentToEntity(entities[i], TestComponent35{});
                break;
            case 34: _engine->addComponentToEntity(entities[i], TestComponent34{});
                _engine->addComponentToEntity(entities[i], TestComponent35{});
                _engine->addComponentToEntity(entities[i], TestComponent36{});
                break;
            case 35: _engine->addComponentToEntity(entities[i], TestComponent35{});
                _engine->addComponentToEntity(entities[i], TestComponent36{});
                _engine->addComponentToEntity(entities[i], TestComponent37{});
                break;
            case 36: _engine->addComponentToEntity(entities[i], TestComponent36{});
                _engine->addComponentToEntity(entities[i], TestComponent37{});
                _engine->addComponentToEntity(entities[i], TestComponent38{});
                break;
            case 37: _engine->addComponentToEntity(entities[i], TestComponent37{});
                _engine->addComponentToEntity(entities[i], TestComponent38{});
                _engine->addComponentToEntity(entities[i], TestComponent39{});
                break;
            case 38: _engine->addComponentToEntity(entities[i], TestComponent38{});
                _engine->addComponentToEntity(entities[i], TestComponent39{});
                _engine->addComponentToEntity(entities[i], TestComponent40{});
                break;
            case 39: _engine->addComponentToEntity(entities[i], TestComponent39{});
                _engine->addComponentToEntity(entities[i], TestComponent40{});
                _engine->addComponentToEntity(entities[i], TestComponent41{});
                break;
            case 40: _engine->addComponentToEntity(entities[i], TestComponent40{});
                _engine->addComponentToEntity(entities[i], TestComponent41{});
                _engine->addComponentToEntity(entities[i], TestComponent42{});
                break;
            case 41: _engine->addComponentToEntity(entities[i], TestComponent41{});
                _engine->addComponentToEntity(entities[i], TestComponent42{});
                _engine->addComponentToEntity(entities[i], TestComponent43{});
                break;
            case 42: _engine->addComponentToEntity(entities[i], TestComponent42{});
                _engine->addComponentToEntity(entities[i], TestComponent43{});
                _engine->addComponentToEntity(entities[i], TestComponent44{});
                break;
            case 43: _engine->addComponentToEntity(entities[i], TestComponent43{});
                _engine->addComponentToEntity(entities[i], TestComponent44{});
                _engine->addComponentToEntity(entities[i], TestComponent45{});
                break;
            case 44: _engine->addComponentToEntity(entities[i], TestComponent44{});
                _engine->addComponentToEntity(entities[i], TestComponent45{});
                _engine->addComponentToEntity(entities[i], TestComponent46{});
                break;
            case 45: _engine->addComponentToEntity(entities[i], TestComponent45{});
                _engine->addComponentToEntity(entities[i], TestComponent46{});
                _engine->addComponentToEntity(entities[i], TestComponent47{});
                break;
            case 46: _engine->addComponentToEntity(entities[i], TestComponent46{});
                _engine->addComponentToEntity(entities[i], TestComponent47{});
                _engine->addComponentToEntity(entities[i], TestComponent48{});
                break;
            case 47: _engine->addComponentToEntity(entities[i], TestComponent47{});
                _engine->addComponentToEntity(entities[i], TestComponent48{});
                _engine->addComponentToEntity(entities[i], TestComponent49{});
                break;
            case 48: _engine->addComponentToEntity(entities[i], TestComponent48{});
                _engine->addComponentToEntity(entities[i], TestComponent49{});
                _engine->addComponentToEntity(entities[i], TestComponent50{});
                break;
            case 49: _engine->addComponentToEntity(entities[i], TestComponent49{});
                _engine->addComponentToEntity(entities[i], TestComponent50{});
                _engine->addComponentToEntity(entities[i], TestComponent51{});
                break;
            case 50: _engine->addComponentToEntity(entities[i], TestComponent50{});
                _engine->addComponentToEntity(entities[i], TestComponent51{});
                _engine->addComponentToEntity(entities[i], TestComponent52{});
                break;
            case 51: _engine->addComponentToEntity(entities[i], TestComponent51{});
                _engine->addComponentToEntity(entities[i], TestComponent52{});
                _engine->addComponentToEntity(entities[i], TestComponent53{});
                break;
            case 52: _engine->addComponentToEntity(entities[i], TestComponent52{});
                _engine->addComponentToEntity(entities[i], TestComponent53{});
                _engine->addComponentToEntity(entities[i], TestComponent54{});
                break;
            case 53: _engine->addComponentToEntity(entities[i], TestComponent53{});
                _engine->addComponentToEntity(entities[i], TestComponent54{});
                _engine->addComponentToEntity(entities[i], TestComponent55{});
                break;
            case 54: _engine->addComponentToEntity(entities[i], TestComponent54{});
                _engine->addComponentToEntity(entities[i], TestComponent55{});
                _engine->addComponentToEntity(entities[i], TestComponent56{});
                break;
            case 55: _engine->addComponentToEntity(entities[i], TestComponent55{});
                _engine->addComponentToEntity(entities[i], TestComponent56{});
                _engine->addComponentToEntity(entities[i], TestComponent57{});
                break;
            case 56: _engine->addComponentToEntity(entities[i], TestComponent56{});
                _engine->addComponentToEntity(entities[i], TestComponent57{});
                _engine->addComponentToEntity(entities[i], TestComponent58{});
                break;
            case 57: _engine->addComponentToEntity(entities[i], TestComponent57{});
                _engine->addComponentToEntity(entities[i], TestComponent58{});
                _engine->addComponentToEntity(entities[i], TestComponent59{});
                break;
            case 58: _engine->addComponentToEntity(entities[i], TestComponent58{});
                _engine->addComponentToEntity(entities[i], TestComponent59{});
                _engine->addComponentToEntity(entities[i], TestComponent60{});
                break;
            case 59: _engine->addComponentToEntity(entities[i], TestComponent59{});
                _engine->addComponentToEntity(entities[i], TestComponent60{});
                _engine->addComponentToEntity(entities[i], TestComponent61{});
                break;
            case 60: _engine->addComponentToEntity(entities[i], TestComponent60{});
                _engine->addComponentToEntity(entities[i], TestComponent61{});
                _engine->addComponentToEntity(entities[i], TestComponent62{});
                break;
            case 61: _engine->addComponentToEntity(entities[i], TestComponent61{});
                _engine->addComponentToEntity(entities[i], TestComponent62{});
                _engine->addComponentToEntity(entities[i], TestComponent63{});
                break;
            case 62: _engine->addComponentToEntity(entities[i], TestComponent62{});
                _engine->addComponentToEntity(entities[i], TestComponent63{});
                _engine->addComponentToEntity(entities[i], TestComponent64{});
                break;
            case 63: _engine->addComponentToEntity(entities[i], TestComponent63{});
                _engine->addComponentToEntity(entities[i], TestComponent64{});
                _engine->addComponentToEntity(entities[i], TestComponent65{});
                break;
            case 64: _engine->addComponentToEntity(entities[i], TestComponent64{});
                _engine->addComponentToEntity(entities[i], TestComponent65{});
                _engine->addComponentToEntity(entities[i], TestComponent66{});
                break;
            case 65: _engine->addComponentToEntity(entities[i], TestComponent65{});
                _engine->addComponentToEntity(entities[i], TestComponent66{});
                _engine->addComponentToEntity(entities[i], TestComponent67{});
                break;
            case 66: _engine->addComponentToEntity(entities[i], TestComponent66{});
                _engine->addComponentToEntity(entities[i], TestComponent67{});
                _engine->addComponentToEntity(entities[i], TestComponent68{});
                break;
            case 67: _engine->addComponentToEntity(entities[i], TestComponent67{});
                _engine->addComponentToEntity(entities[i], TestComponent68{});
                _engine->addComponentToEntity(entities[i], TestComponent69{});
                break;
            case 68: _engine->addComponentToEntity(entities[i], TestComponent68{});
                _engine->addComponentToEntity(entities[i], TestComponent69{});
                _engine->addComponentToEntity(entities[i], TestComponent70{});
                break;
            case 69: _engine->addComponentToEntity(entities[i], TestComponent69{});
                _engine->addComponentToEntity(entities[i], TestComponent70{});
                _engine->addComponentToEntity(entities[i], TestComponent71{});
                break;
            case 70: _engine->addComponentToEntity(entities[i], TestComponent70{});
                _engine->addComponentToEntity(entities[i], TestComponent71{});
                _engine->addComponentToEntity(entities[i], TestComponent72{});
                break;
            case 71: _engine->addComponentToEntity(entities[i], TestComponent71{});
                _engine->addComponentToEntity(entities[i], TestComponent72{});
                _engine->addComponentToEntity(entities[i], TestComponent73{});
                break;
            case 72: _engine->addComponentToEntity(entities[i], TestComponent72{});
                _engine->addComponentToEntity(entities[i], TestComponent73{});
                _engine->addComponentToEntity(entities[i], TestComponent74{});
                break;
            case 73: _engine->addComponentToEntity(entities[i], TestComponent73{});
                _engine->addComponentToEntity(entities[i], TestComponent74{});
                _engine->addComponentToEntity(entities[i], TestComponent75{});
                break;
            case 74: _engine->addComponentToEntity(entities[i], TestComponent74{});
                _engine->addComponentToEntity(entities[i], TestComponent75{});
                _engine->addComponentToEntity(entities[i], TestComponent76{});
                break;
            case 75: _engine->addComponentToEntity(entities[i], TestComponent75{});
                _engine->addComponentToEntity(entities[i], TestComponent76{});
                _engine->addComponentToEntity(entities[i], TestComponent77{});
                break;
            case 76: _engine->addComponentToEntity(entities[i], TestComponent76{});
                _engine->addComponentToEntity(entities[i], TestComponent77{});
                _engine->addComponentToEntity(entities[i], TestComponent78{});
                break;
            case 77: _engine->addComponentToEntity(entities[i], TestComponent77{});
                _engine->addComponentToEntity(entities[i], TestComponent78{});
                _engine->addComponentToEntity(entities[i], TestComponent79{});
                break;
            case 78: _engine->addComponentToEntity(entities[i], TestComponent78{});
                _engine->addComponentToEntity(entities[i], TestComponent79{});
                _engine->addComponentToEntity(entities[i], TestComponent80{});
                break;
            case 79: _engine->addComponentToEntity(entities[i], TestComponent79{});
                _engine->addComponentToEntity(entities[i], TestComponent80{});
                _engine->addComponentToEntity(entities[i], TestComponent81{});
                break;
            case 80: _engine->addComponentToEntity(entities[i], TestComponent80{});
                _engine->addComponentToEntity(entities[i], TestComponent81{});
                _engine->addComponentToEntity(entities[i], TestComponent82{});
                break;
            case 81: _engine->addComponentToEntity(entities[i], TestComponent81{});
                _engine->addComponentToEntity(entities[i], TestComponent82{});
                _engine->addComponentToEntity(entities[i], TestComponent83{});
                break;
            case 82: _engine->addComponentToEntity(entities[i], TestComponent82{});
                _engine->addComponentToEntity(entities[i], TestComponent83{});
                _engine->addComponentToEntity(entities[i], TestComponent84{});
                break;
            case 83: _engine->addComponentToEntity(entities[i], TestComponent83{});
                _engine->addComponentToEntity(entities[i], TestComponent84{});
                _engine->addComponentToEntity(entities[i], TestComponent85{});
                break;
            case 84: _engine->addComponentToEntity(entities[i], TestComponent84{});
                _engine->addComponentToEntity(entities[i], TestComponent85{});
                _engine->addComponentToEntity(entities[i], TestComponent86{});
                break;
            case 85: _engine->addComponentToEntity(entities[i], TestComponent85{});
                _engine->addComponentToEntity(entities[i], TestComponent86{});
                _engine->addComponentToEntity(entities[i], TestComponent87{});
                break;
            case 86: _engine->addComponentToEntity(entities[i], TestComponent86{});
                _engine->addComponentToEntity(entities[i], TestComponent87{});
                _engine->addComponentToEntity(entities[i], TestComponent88{});
                break;
            case 87: _engine->addComponentToEntity(entities[i], TestComponent87{});
                _engine->addComponentToEntity(entities[i], TestComponent88{});
                _engine->addComponentToEntity(entities[i], TestComponent89{});
                break;
            case 88: _engine->addComponentToEntity(entities[i], TestComponent88{});
                _engine->addComponentToEntity(entities[i], TestComponent89{});
                _engine->addComponentToEntity(entities[i], TestComponent90{});
                break;
            case 89: _engine->addComponentToEntity(entities[i], TestComponent89{});
                _engine->addComponentToEntity(entities[i], TestComponent90{});
                _engine->addComponentToEntity(entities[i], TestComponent91{});
                break;
            case 90: _engine->addComponentToEntity(entities[i], TestComponent90{});
                _engine->addComponentToEntity(entities[i], TestComponent91{});
                _engine->addComponentToEntity(entities[i], TestComponent92{});
                break;
            case 91: _engine->addComponentToEntity(entities[i], TestComponent91{});
                _engine->addComponentToEntity(entities[i], TestComponent92{});
                _engine->addComponentToEntity(entities[i], TestComponent93{});
                break;
            case 92: _engine->addComponentToEntity(entities[i], TestComponent92{});
                _engine->addComponentToEntity(entities[i], TestComponent93{});
                _engine->addComponentToEntity(entities[i], TestComponent94{});
                break;
            case 93: _engine->addComponentToEntity(entities[i], TestComponent93{});
                _engine->addComponentToEntity(entities[i], TestComponent94{});
                _engine->addComponentToEntity(entities[i], TestComponent95{});
                break;
            case 94: _engine->addComponentToEntity(entities[i], TestComponent94{});
                _engine->addComponentToEntity(entities[i], TestComponent95{});
                _engine->addComponentToEntity(entities[i], TestComponent96{});
                break;
            case 95: _engine->addComponentToEntity(entities[i], TestComponent95{});
                _engine->addComponentToEntity(entities[i], TestComponent96{});
                _engine->addComponentToEntity(entities[i], TestComponent97{});
                break;
            case 96: _engine->addComponentToEntity(entities[i], TestComponent96{});
                _engine->addComponentToEntity(entities[i], TestComponent97{});
                _engine->addComponentToEntity(entities[i], TestComponent98{});
                break;
            case 97: _engine->addComponentToEntity(entities[i], TestComponent97{});
                _engine->addComponentToEntity(entities[i], TestComponent98{});
                _engine->addComponentToEntity(entities[i], TestComponent99{});
                break;
            case 98: _engine->addComponentToEntity(entities[i], TestComponent98{});
                _engine->addComponentToEntity(entities[i], TestComponent99{});
                _engine->addComponentToEntity(entities[i], TestComponent0{});
                break;
            case 99: _engine->addComponentToEntity(entities[i], TestComponent99{});
                _engine->addComponentToEntity(entities[i], TestComponent0{});
                _engine->addComponentToEntity(entities[i], TestComponent1{});
                break;
            }
        }
    }
};

#endif
